# Secret for Postgres authentication
apiVersion: v1

# Secret for Postgres authentication
kind: Secret

# Secret for Postgres authentication
metadata:
  # Name of the secret
  name: {{ include "gapCanvasPostgres.fullname" . }}-auth
  # Labels for the secret
  labels:
    {{- include "gapCanvasPostgres.labels" . | nindent 4 }}

# Secret type and data
type: Opaque
stringData:
  # Postgres official image reads these variables on first initialization
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}